site_name: 'CharjaBox'
site_description: 'Work in progress Ansible based Homeserver setup using Docker.'
site_author: 'CherryKitten'
repo_url: 'https://github.com/CherryKitten/CharjaBox'

theme: 'cinder'

nav:
  - Home: 'index.md'
  - Requirements: 'requirements.md'
  - Configuration: 'configuration.md'
  - Installation: 'installation.md'
  - Contributing: 'contributing.md'
  - Applications:
      - Heimdall: 'applications/heimdall.md'
      - SMB: 'applications/smb.md'
      - Nextcloud: 'applications/nextcloud.md'
      - Miniflux: 'applications/miniflux.md'
      - Firefly III: 'applications/firefly.md'
      - Lancache: 'applications/lancache.md'
      - Tautulli: 'applications/tautulli.md'
      - Development:
        - Dokuwiki: 'applications/dokuwiki.md'
        - Gitea: 'applications/gitea.md'
      - Downloading:
        - r(u)torrent: 'applications/rtorrent.md'
      - Home Automation:
        - Home-Assistant: 'applications/homeassistant.md'
      - Media streaming:
        - Airsonic: 'applications/airsonic.md'
        - Plex: 'applications/plex.md'
        - Jellyfin: 'applications/jellyfin.md'
        - Calibre-Web: 'applications/calibre.md'
      - Media management:
        - Jackett: 'applications/jackett.md'
        - Radarr: 'applications/radarr.md'
        - Sonarr: 'applications/sonarr.md'
        - Lidarr: 'applications/lidarr.md'
        - Bazarr: 'applications/bazarr.md'
      - Server & Network management:
        - Portainer: 'applications/portainer.md'
        - BIND: 'applications/bind.md'
      - Security & Backup:
        - Bitwarden_rs: 'applications/bitwarden_rs.md'
        - Timemachine: 'applications/timemachine.md'
      - Webservers & reverse proxies:
        - Nginx: 'applications/nginx.md'
        - Traefik: 'applications/traefik.md'
