site_name: 'CharjaBox'
site_description: 'Work in progress Ansible based Homeserver setup using Docker.'
site_author: 'CherryKitten'
repo_url: 'https://github.com/CherryKitten/CharjaBox'

theme: 'windmill-dark'

nav:
  - Home: 'index.md'
  - 'requirements.md'
  - 'configuration.md'
  - 'installation.md'
  - 'contributing.md'
  - Applications:
      - 'applications/nginx.md'
      - 'applications/portainer.md'
      - 'applications/smb.md'
      - 'applications/plex.md'
      - 'applications/bind.md'
      - 'applications/rtorrent.md'
      - 'applications/dokuwiki.md'
      - 'applications/timemachine.md'
      - 'applications/gitea.md'
      - 'applications/lancache.md'
      - Media management:
          - 'applications/jackett.md'
          - 'applications/radarr.md'
          - 'applications/sonarr.md'
          - 'applications/lidarr.md'
