site_name: 'CharjaBox'
site_description: 'Work in progress Ansible based Homeserver setup using Docker.'
site_author: 'CherryKitten'
repo_url: 'https://github.com/CherryKitten/CharjaBox'

theme: 'cinder'

nav:
  - Home: 'index.md'
  - Requirements: 'requirements.md'
  - Configuration: 'configuration.md'
  - Installation: 'installation.md'
  - Contributing: 'contributing.md'
  - Applications:
      - SMB: 'applications/smb.md'
      - r(u)torrent: 'applications/rtorrent.md'
      - Dokuwiki: 'applications/dokuwiki.md'
      - Gitea: 'applications/gitea.md'
      - Lancache: 'applications/lancache.md'
      - Media streaming:
          - Airsonic: 'applications/airsonic.md'
          - Plex: 'applications/plex.md'
      - Media management:
          - Jackett: 'applications/jackett.md'
          - Radarr: 'applications/radarr.md'
          - Sonarr: 'applications/sonarr.md'
          - Lidarr: 'applications/lidarr.md'
          - Bazarr: 'applications/bazarr.md'
      - Server & Network management:
          - Portainer: 'applications/portainer.md'
          - BIND: 'applications/bind.md'
      - Security & Backup:
          - Bitwarden_rs: 'applications/bitwarden_rs.md'
          - Timemachine: 'applications/timemachine.md'
      - Webservers & reverse proxies:
          - Nginx: 'applications/nginx.md'
          - Traefik: 'applications/traefik.md'
