- name: Initialize an empty list for enabled apps
  set_fact:
    apps_enabled: []

- name: Initialize an empty list for disabled apps
  set_fact:
    apps_disabled: []

- name: Append enabled apps to list
  set_fact:
    apps_enabled: "{{ apps_enabled + [  item  ] }}"
  loop: "{{ apps }}"
  when: 'lookup("vars", item + "_enabled")'

- name: Append disabled apps to list
  set_fact:
    apps_disabled: "{{ apps_disabled + [  item  ] }}"
  loop: "{{ apps }}"
  when: 'not lookup("vars", item + "_enabled")'

#- name: "Make sure {{ item }} is not running"
#  systemd:
#    name: "{{ item }}"
#    enabled: false
#    daemon-reload: true
#    state: stopped
#  loop: "{{ apps_disabled }}"
