---
- name: create lidarr directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ lidarr_data_directory }}"
    - "{{ lidarr_config_directory }}"

- name: create lidarr docker-compose directory
  file:
    path: "{{ docker_compose_dir }}/lidarr"
    state: directory

- name: copy docker-compose.yml for lidarr
  template:
    src: docker-compose.lidarr.yml.j2
    dest: "{{ docker_compose_dir }}/lidarr/docker-compose.lidarr.yml"

- name: configure lidarr systemd service
  template:
    src: lidarr.service.j2
    dest: /etc/systemd/system/lidarr.service

- name: start lidarr
  systemd:
    name: lidarr
    enabled: "yes"
    daemon-reload: "yes"
    state: started
