airsonic_port: 4040

bazarr_port: 6767

bind_webmin_port: 10000

bitwarden_rs_http_port: 9001
bitwarden_rs_websocket_port: 3012

calibre_port: 8083

dokuwiki_http_port: 6009
dokuwiki_https_port: 6010

duplicati_port: 8200

firefly_port: 4005

gitea_http_port: 3000
gitea_ssh_port: 222

heimdall_http_port: 4000
heimdall_https_port: 4001

homeassistant_port: 8123

jackett_port: 9117

jellyfin_http_port: 6005
jellyfin_https_port: 6006

lancache_port: 6666

miniflux_port: 8778

nextcloud_port: 8380

nginx_http_port: 80
nginx_https_port: 443

openvpn_port: "1194"

plex_web_port: 32400

portainer_port: 9000

posteio_smtp_port: 25
posteio_http_port: 8183
posteio_pop3_port: 110
posteio_imap_port: 143
posteio_https_port: 8184
posteio_smtps_port: 465
posteio_msa_port: 587
posteio_imaps_port: 993
posteio_pop3s_port: 995
posteio_sieve_port: 4190

pyload_port: 8001

rtorrent_http_port: 7991
rtorrent_https_port: 7992
rtorrent_scgi_port: 5000
rtorrent_bittorrent_port: 51413
rtorrent_bittorrent_port2: 6881

lidarr_port: 8686

radarr_port: 7878

sonarr_port: 8989

tautulli_port: 8181

thelounge_port: 7743

timemachine_port: 10445

traefik_http_port: 80
traefik_https_port: 443
traefik_webinterface_port: 8080
