miniflux_enabled: false

miniflux_tag: "latest"
miniflux_db_tag: 11.1
miniflux_directories:
  data: "{{ docker_home }}/miniflux/data"

miniflux_db_password: ""

miniflux_admin_username: "Admin"
miniflux_admin_password: ""

miniflux_traefik_enabled: false
miniflux_domain: "miniflux.{{ charjabox_domain }}"
