---
- name: create portainer directory
  file:
    path: "{{ portainer_config_directory }}"
    state: directory

- name: create portainer docker-compose directory
  file:
    path: "{{ docker_compose_dir }}/portainer"
    state: directory

- name: copy docker-compose.yml for portainer
  template:
    src: docker-compose.portainer.yml.j2
    dest: "{{ docker_compose_dir }}/portainer/docker-compose.portainer.yml"

- name: configure portainer systemd service
  template:
    src: portainer.service.j2
    dest: /etc/systemd/system/portainer.service

- name: start portainer
  systemd:
    name: portainer
    enabled: "yes"
    daemon-reload: "yes"
    state: started
