---
- name: install dependencies
  apt:
    name: "{{charjabox_packages}}"
  tags:
    - dependencies

- name: set hostname
  hostname:
    name: "{{charjabox_hostname}}"

- name: configure timezone
  timezone:
    name: "{{Â charjabox_timezone }}"

- name: create charjabox group
  group:
    name: charjabox
    state: present

- name: create charjabox user
  user:
    name: charjabox
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: charjabox
    shell: /usr/sbin/nologin

- name: set permissions for shares
  file:
    path: "{{ item.path }}"
    owner: charjabox
    group: charjabox
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"
